// Main application file for the Express server
// Sets up middleware, routes, and database connection
var createError = require('http-errors');
var express = require('express');
var path = require('path');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var indexRouter = require('./routes/index');
var usersRouter = require('./routes/users');
const bcrypt = require('bcrypt');

// Database connection exported from connect.js (sqlite3 instance)
const { DB } = require('./connect');
// Server port (can be overridden by environment variable)
const PORT = process.env.PORT || 3000;
var app = express();

// view engine setup

app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

// Mount standard routers generated by Express generator
app.use('/', indexRouter);
app.use('/users', usersRouter);

// Get all flashcards
// Responds with JSON: { flashcards: [...] }
// This endpoint retrieves all flashcards from the database. It now includes the deck name
// (if any) as `DeckName` so clients can display the deck without an extra lookup.
app.get('/api', (req, res) => {
  const sql = `SELECT flashcard.*, deck.Name AS DeckName FROM flashcard LEFT JOIN deck ON flashcard.DeckID = deck.DeckID`;
  DB.all(sql, [], (err, rows) => {
    if (err) {
      console.error(err.message);
      return res.status(500).json({ error: err.message });
    }
    res.json({ flashcards: rows });
  });
});

// Get a random flashcard
// Responds with JSON: { flashcard: { CardID, Front, Back, Reaction } }
// This endpoint retrieves a single random flashcard from the database.
app.get('/api/random', (req, res) => {
  const sql = 'SELECT * FROM flashcard ORDER BY RANDOM() LIMIT 1';
  DB.get(sql, [], (err, row) => {
    if (err) {
      console.error(err.message);
      return res.status(500).json({ error: err.message });
    }
    if (!row) {
      return res.status(404).json({ message: 'No flashcards found' });
    }
    res.json({ flashcard: row });
  });
});

// Get statistics
// Responds with JSON: { totalCards, totalDecks, masteredCards, strugglingCards }
// This endpoint aggregates statistics for the dashboard.
app.get('/api/stats', (req, res) => {
  const stats = {};
  
  // Parallelize queries for efficiency
  const p1 = new Promise((resolve, reject) => {
    DB.get(
      `SELECT 
        COUNT(*) as total, 
        SUM(CASE WHEN Reaction = 'great' THEN 1 ELSE 0 END) as mastered,
        SUM(CASE WHEN Reaction IN ('hard', 'again') THEN 1 ELSE 0 END) as struggling
       FROM flashcard`,
      [],
      (err, row) => {
        if (err) reject(err);
        else resolve(row);
      }
    );
  });

  const p2 = new Promise((resolve, reject) => {
    DB.get('SELECT COUNT(*) as count FROM deck', [], (err, row) => {
      if (err) reject(err);
      else resolve(row ? row.count : 0);
    });
  });

  Promise.all([p1, p2])
    .then(([cardStats, deckCount]) => {
      res.json({
        totalCards: cardStats ? cardStats.total : 0,
        masteredCards: cardStats ? cardStats.mastered || 0 : 0,
        strugglingCards: cardStats ? cardStats.struggling || 0 : 0,
        totalDecks: deckCount
      });
    })
    .catch((err) => {
      console.error('Stats query error:', err.message);
      res.status(500).json({ error: err.message });
    });
});

// Get a single flashcard by CardID
// Example: GET /api/3
// This endpoint retrieves a specific flashcard by its ID.
app.get('/api/:id(\\d+)', (req, res) => {
  const id = req.params.id;
  const sql = 'SELECT * FROM flashcard WHERE CardID = ?';
  DB.get(sql, [id], (err, row) => {
    if (err) {
      console.error(err.message);
      return res.status(500).json({ error: err.message });
    }
    if (!row) {
      return res.status(404).json({ message: `Flashcard with ID ${id} not found` });
    }
    res.json({ flashcard: row });
  });
});

// Add a new flashcard
// Expects JSON body: { Front, Back, Reaction }
// This endpoint creates a new flashcard in the database.
app.post('/api', (req, res) => {
  const { Front, Back, Reaction, DeckID } = req.body;
  console.log('POST /api received:', { Front, Back, Reaction, DeckID });

  if (!Front || !Back || !Reaction || !DeckID) {
    return res.status(400).json({ error: 'Front, Back, Reaction and DeckID are required' });
  }

  const sql = 'INSERT INTO flashcard (DeckID, Front, Back, Reaction) VALUES (?, ?, ?, ?)';
  DB.run(sql, [DeckID, Front, Back, Reaction], function (err) {
    if (err) {
      console.error(err.message);
      return res.status(500).json({ error: err.message });
    }
    res.status(201).json({
      message: `Flashcard created with ID ${this.lastID}`,
      CardID: this.lastID
    });
  });
});

// Get all decks
// Responds with JSON: { decks: [...] }
// This endpoint retrieves all decks from the database.
app.get('/api/decks', (req, res) => {
  const sql = 'SELECT * FROM deck';
  DB.all(sql, [], (err, rows) => {
    if (err) {
      console.error(err.message);
      return res.status(500).json({ error: err.message });
    }
    res.json({ decks: rows });
  });
});

// Create a new deck
// Expects JSON body: { Name }
// This endpoint creates a new deck in the database.
app.post('/api/decks', (req, res) => {
  const { Name, Username } = req.body;
  if (!Name) {
    return res.status(400).json({ error: 'Name is required' });
  }
  const sql = 'INSERT INTO deck (Name, Username) VALUES (?, ?)';
  DB.run(sql, [Name, Username], function (err) {
    if (err) {
      console.error(err.message);
      return res.status(500).json({ error: err.message });
    }
    res.status(201).json({ message: 'Deck created', DeckID: this.lastID, deck: { DeckID: this.lastID, Name } });
  });
});



// Delete a flashcard by CardID
// Uses query parameter `id`, e.g. DELETE /api?id=3
// This endpoint deletes a flashcard from the database by its ID.
app.delete('/api', (req, res) => {
  const id = req.query.id;

  if (!id) {
    return res.status(400).json({ error: 'Missing id in query' });
  }

  const sql = 'DELETE FROM flashcard WHERE CardID = ?';
  DB.run(sql, [id], function (err) {
    if (err) {
      console.error(err.message);
      return res.status(500).json({ error: err.message });
    }

    if (this.changes === 0) {
      return res.status(404).json({ message: `Flashcard with ID ${id} not found` });
    }

    res.status(200).json({ message: `Flashcard ${id} deleted` });
  });
});

// Get a random spaced repetition card
// Currently behaves same as random, but intended for spaced repetition logic
app.get('/api/spacedcard', (req, res) => {
  const sql = 'SELECT * FROM flashcard ORDER BY RANDOM() LIMIT 1';
  DB.get(sql, [], (err, row) => {
    if (err) {
      console.error(err.message);
      return res.status(500).json({ error: err.message });
    }
    if (!row) {
      return res.status(404).json({ message: 'No flashcards found' });
    }
    res.json({ flashcard: row });
  });
});

// /api/stats route moved earlier to avoid matching /api/:id
// (keeps routes specific and prevents accidental parameter collisions)


// Register new user
app.post('/api/register', (req, res) => {
  const { username, password } = req.body;
  if (!username || !password) {
    return res.status(400).json({ error: 'username and password required' });
  }

  DB.get('SELECT Username FROM users WHERE Username = ?', [username], (err, row) => {
    if (err) {
      console.error('User check error:', err.message);
      return res.status(500).json({ error: err.message });
    }

    if (row) {
      return res.status(409).json({ error: 'username already exists' });
    }

    bcrypt.hash(password, 10, (hashErr, hash) => {
      if (hashErr) {
        console.error('Hash error:', hashErr.message);
        return res.status(500).json({ error: hashErr.message });
      }

      DB.run('INSERT INTO users (Username, PasswordHash) VALUES (?, ?)', [username, hash], function (insErr) {
        if (insErr) {
          console.error('User insert error:', insErr.message);
          return res.status(500).json({ error: insErr.message });
        }

        // Create a personal default deck for the user (optional)
        
            // don't fail registration for deck error
          
          return res.status(201).json({ message: 'User created' });
        });
      });
    });
  });


// catch 404 and forward to error handler
app.use(function(req, res, next) {
  next(createError(404));
});

// error handler
app.use(function(err, req, res, next) {
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};
  res.status(err.status || 500);
  res.render('error');
});

app.listen(PORT, () => {
  console.log(`Server running at http://localhost:${PORT}`);
});








module.exports = app;
