// Main application file for the Express server
// Sets up middleware, routes, and database connection
var createError = require('http-errors');
var express = require('express');
var path = require('path');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var indexRouter = require('./routes/index');
var usersRouter = require('./routes/users');

// Database connection exported from connect.js (sqlite3 instance)
const { DB } = require('./connect');
// Server port (can be overridden by environment variable)
const PORT = process.env.PORT || 3000;
var app = express();

// view engine setup

app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

// Mount standard routers generated by Express generator
app.use('/', indexRouter);
app.use('/users', usersRouter);

// Get all flashcards
// Responds with JSON: { flashcards: [...] }
// This endpoint retrieves all flashcards from the database.
app.get('/api', (req, res) => {
  const sql = 'SELECT * FROM flashcard';
  DB.all(sql, [], (err, rows) => {
    if (err) {
      console.error(err.message);
      return res.status(500).json({ error: err.message });
    }
    res.json({ flashcards: rows });
  });
});

// Get a random flashcard
// Responds with JSON: { flashcard: { CardID, Front, Back, Reaction } }
// This endpoint retrieves a single random flashcard from the database.
app.get('/api/random', (req, res) => {
  const sql = 'SELECT * FROM flashcard ORDER BY RANDOM() LIMIT 1';
  DB.get(sql, [], (err, row) => {
    if (err) {
      console.error(err.message);
      return res.status(500).json({ error: err.message });
    }
    if (!row) {
      return res.status(404).json({ message: 'No flashcards found' });
    }
    res.json({ flashcard: row });
  });
});

// Get a single flashcard by CardID
// Example: GET /api/3
// This endpoint retrieves a specific flashcard by its ID.
app.get('/api/:id', (req, res) => {
  const id = req.params.id;
  const sql = 'SELECT * FROM flashcard WHERE CardID = ?';
  DB.get(sql, [id], (err, row) => {
    if (err) {
      console.error(err.message);
      return res.status(500).json({ error: err.message });
    }
    if (!row) {
      return res.status(404).json({ message: `Flashcard with ID ${id} not found` });
    }
    res.json({ flashcard: row });
  });
});

// Add a new flashcard
// Expects JSON body: { Front, Back, Reaction }
// This endpoint creates a new flashcard in the database.
app.post('/api', (req, res) => {
  const { Front, Back, Reaction, DeckID } = req.body;
  console.log('POST /api received:', { Front, Back, Reaction, DeckID });

  if (!Front || !Back || !Reaction || !DeckID) {
    return res.status(400).json({ error: 'Front, Back, Reaction and DeckID are required' });
  }

  const sql = 'INSERT INTO flashcard (DeckID, Front, Back, Reaction) VALUES (?, ?, ?, ?)';
  DB.run(sql, [DeckID, Front, Back, Reaction], function (err) {
    if (err) {
      console.error(err.message);
      return res.status(500).json({ error: err.message });
    }
    res.status(201).json({
      message: `Flashcard created with ID ${this.lastID}`,
      CardID: this.lastID
    });
  });
});

// Get all decks
// Responds with JSON: { decks: [...] }
// This endpoint retrieves all decks from the database.
app.get('/api/decks', (req, res) => {
  const sql = 'SELECT * FROM deck';
  DB.all(sql, [], (err, rows) => {
    if (err) {
      console.error(err.message);
      return res.status(500).json({ error: err.message });
    }
    res.json({ decks: rows });
  });
});

// Create a new deck
// Expects JSON body: { Name }
// This endpoint creates a new deck in the database.
app.post('/api/decks', (req, res) => {
  const { Name, Username } = req.body;
  if (!Name) {
    return res.status(400).json({ error: 'Name is required' });
  }
  const sql = 'INSERT INTO deck (Name, Username) VALUES (?, ?)';
  DB.run(sql, [Name, Username], function (err) {
    if (err) {
      console.error(err.message);
      return res.status(500).json({ error: err.message });
    }
    res.status(201).json({ message: 'Deck created', DeckID: this.lastID, deck: { DeckID: this.lastID, Name } });
  });
});











// Delete a flashcard by CardID
// Uses query parameter `id`, e.g. DELETE /api?id=3
// This endpoint deletes a flashcard from the database by its ID.
app.delete('/api', (req, res) => {
  const id = req.query.id;

  if (!id) {
    return res.status(400).json({ error: 'Missing id in query' });
  }

  const sql = 'DELETE FROM flashcard WHERE CardID = ?';
  DB.run(sql, [id], function (err) {
    if (err) {
      console.error(err.message);
      return res.status(500).json({ error: err.message });
    }

    if (this.changes === 0) {
      return res.status(404).json({ message: `Flashcard with ID ${id} not found` });
    }

    res.status(200).json({ message: `Flashcard ${id} deleted` });
  });
});

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  next(createError(404));
});

// error handler
app.use(function(err, req, res, next) {
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};
  res.status(err.status || 500);
  res.render('error');
});

app.listen(PORT, () => {
  console.log(`Server running at http://localhost:${PORT}`);
});

// Get a random spaced repetition card
// Currently behaves same as random, but intended for spaced repetition logic
app.get('/api/spacedcard', (req, res) => {
  const sql = 'SELECT * FROM flashcard ORDER BY RANDOM() LIMIT 1';
  DB.get(sql, [], (err, row) => {
    if (err) {
      console.error(err.message);
      return res.status(500).json({ error: err.message });
    }
    if (!row) {
      return res.status(404).json({ message: 'No flashcards found' });
    }
    res.json({ flashcard: row });
  });
});






module.exports = app;
